#    Universidade Federal do Amazonas - UFAM
#    Disciplina: Programação de Sistemas de Tempo Real - PTR
#    Author: Edson Nascimento Silva Neto - 21350694
#		 Evaldo Patrik dos Santos Cardoso - 21453640
#

all: Lab2

Lab2: matrix.c lab2.c  #arquivos de  dependencia
	clear
	rm -rf Lab2
	gcc -o Lab2 matrix.c lab2.c

exec: Lab2
	./Lab2

clean: #remove arquivo somasub
	rm -rf Lab2
	clear
